In [24]:
import numpy as np

In [ ]:
#PART-1

In [121]:
# 1) Use 2 approaches to create a 2D array with shape (3,2) in one line, the values are [1, 6].         2 points
#     One is a Python range(); Another is NumPy arange() or other NumPy functions.
#     Note: if you use more than 1 line code to complete it, no point.

In [26]:
#Creating 2D array using Python range():
x = [[i, i + 1] for i in range(1, 7, 2)]
print(x)

[[1, 2], [3, 4], [5, 6]]


In [27]:
#Creating 2D array using NumPy arange()
x=np.arange(1,7).reshape((3,2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
# 2) Use one line to create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.           1 point   

In [29]:
x= np.mean(np.arange(2,101,2))
print(x)

51.0


In [ ]:
# 3) Create an 3x3x3 array filled with arbitrary float numbers and set seed=100; and find the minimum and maximum values. 

In [36]:
rng = np.random.default_rng(seed=100)  #creating 3x3x3 array
x=rng.random((3,3,3))
print(x)

[[[0.83498163 0.59655403 0.28886324]
  [0.04295157 0.9736544  0.5964717 ]
  [0.79026316 0.91033938 0.68815445]]

 [[0.18999147 0.98147898 0.28474005]
  [0.62927317 0.58103648 0.59991227]
  [0.53524811 0.9957771  0.50194608]]

 [[0.77102258 0.49416178 0.99767449]
  [0.97862192 0.39356804 0.32192526]
  [0.86218065 0.7993249  0.69143063]]]


In [38]:
print(np.min(x))        # finding minimum

0.042951570694211405


In [39]:
print(np.max(x))       # finding maximum

0.9976744931721895


In [ ]:
# 4) Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.    2 points

In [42]:
x=np.arange(5,5+3*10,3)
print(x)

[ 5  8 11 14 17 20 23 26 29 32]


In [ ]:
# 5) Create a shape (10,10) array with arbitrary values; and find the memory size of this array.    1 point

In [50]:
x=np.random.rand(10,10)   #creating 10x10 arbitary array
x

array([[0.17621717, 0.36989073, 0.12475032, 0.96196115, 0.26907842,
        0.66590482, 0.71713438, 0.56980646, 0.50934286, 0.74858466],
       [0.79049489, 0.51169491, 0.20602605, 0.68852174, 0.36117672,
        0.49620407, 0.87646582, 0.17141693, 0.02318241, 0.90666171],
       [0.76786895, 0.71747235, 0.41643688, 0.27159254, 0.12255972,
        0.20115412, 0.58339754, 0.87911401, 0.28900634, 0.82490255],
       [0.96951528, 0.83002211, 0.20934331, 0.76026009, 0.83500262,
        0.12050297, 0.08751887, 0.29764958, 0.44170485, 0.84250331],
       [0.28962837, 0.22690478, 0.32088214, 0.5716614 , 0.48837405,
        0.1213804 , 0.27102199, 0.87511117, 0.5623516 , 0.5567107 ],
       [0.76237197, 0.66474492, 0.72438958, 0.01357265, 0.51680836,
        0.97492235, 0.72036973, 0.74591654, 0.81838026, 0.02126976],
       [0.71151824, 0.16310604, 0.45949317, 0.86657514, 0.0221163 ,
        0.88644885, 0.94931027, 0.40176982, 0.03377475, 0.58300715],
       [0.73443751, 0.31110844, 0.2901913

In [55]:
x.nbytes  #Memory size of the array
x.itemsize*x.size #alternate solution

800

In [ ]:
# 6) Create a 1-d array of size 10 with arbitrary values but the fifth value should be 5.    1 point

In [431]:
x=np.random.rand(10)   
x[4] = 5
print(x)

[0.41182717 0.00785889 0.8335232  0.89881956 5.         0.60532874
 0.24272405 0.55090647 0.71173452 0.78382516]


In [ ]:
# 7) Create an array with values ranging from 10 to 49 (included); and reverse it then (first element becomes last).    1 point

In [69]:
x= np.arange(10,50)
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# 8) Use one line to create a 5x5 matrix with row values ranging from 0 to 4:           2 points

In [73]:
x = np.zeros((5,5)) + np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [425]:
# 9) We have a 7x7 zero 2D array, please use one line code to get the following matrix:  2 points

In [423]:
x = np.pad(np.ones((5,5)), [(1,1), (1,1)])  #using np.pad() function to pad array by padding around 5x5 np.ones array
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 10). Create a 5x5 2-d array with values 1,2,3,4,5 on the diagonal. 
#        Then, make 1,2,3,4,5 move below the diagonal.            2 points

In [99]:
x = np.diag([1,2,3,4,5]) #creating 5x5 array
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [100]:
x = np.diag([1,2,3,4,5],-1) #moving it below diagonal
print(x)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [ ]:
# 11) Given a random array with shape(4,5) and values [0,1), please use this array to subtract its mean of each row. 2 points

In [402]:
x = np.random.rand(4,5)
print('Array is:')
print(x)
mean = x.mean(axis=1, keepdims=True)
result = x - mean
print('Result is:')
print(result)

Array is:
[[0.5992414  0.32556513 0.29087699 0.54626566 0.9359954 ]
 [0.63110398 0.50628287 0.82198988 0.30836744 0.23007017]
 [0.1703366  0.42895027 0.08852986 0.38305553 0.52012086]
 [0.95333504 0.91721114 0.13373734 0.91886977 0.90716388]]
Result is:
[[ 0.05965249 -0.21402379 -0.24871193  0.00667674  0.39640648]
 [ 0.13154111  0.00672     0.32242701 -0.19119542 -0.2694927 ]
 [-0.14786203  0.11075165 -0.22966876  0.06485691  0.20192223]
 [ 0.18727161  0.1511477  -0.6323261   0.15280634  0.14110045]]


In [ ]:
#PART-2

In [ ]:
# 1) Find the index of 5th repetition of number 1 in the given array x.          4 points
# x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]

In [122]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
i =np.where(x == 1)[0][4]   # using numpy where() function
print(i)

8


In [ ]:
# 2) Use np.arange to get an array [1, 2, 3, ..., 9]. Split x into 3 sub-arrays, the length of each sub-array is 4, 2, and 3    2 points

In [131]:
x=np.arange(1,10)
a=np.split(x,[4,6])
print(a)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


In [ ]:
# 3) Use arange to generate the following 2D array:     2 points

In [133]:
x=np.arange(16).reshape(4,4)   #Creating the array
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [135]:
a= np.split(x,[1],axis=1)  #Splitting the array
print(a)

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])]


In [ ]:
#4). Given a 2D array:                           6 points

#    [[5,10,15],

#    [20,25,30],

#    [35,40,45]]

#(1) Slicing to get the sub-array [[10,15],[25,30]] by regular indexing.           [2p]

#(2) To get the above sub-array by fancy indexing.     [4p] 

In [136]:
x = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(x)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [140]:
print(x[:2,1:]) #Slicing

[[10 15]
 [25 30]]


In [144]:
row= np.array([[0,0],[1,1]])  #Fancy Indexing
col= np.array([[1,2],[1,2]])
print(x[row,col])

[[10 15]
 [25 30]]


In [ ]:
# 5) Concatenate x and y so that a new array looks like     1 point
#    [[1, 2, 3, 7, 8, 9],
#    [4, 5, 6, 10, 11, 12]]

In [150]:
x= np.array([[ 1, 2 ,3],[ 4 ,5 ,6]])
y= np.array([[ 7 ,8 ,9],[10 ,11 ,12]])
z= np.concatenate((x,y),axis=1)
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# 6) Given a 2D array with shape(5,3) and values [1,10), calculate the min/max (min is divided by max) for each row.   2 point

In [151]:
rng=np.random.default_rng(seed=5)
x= rng.random((5,3))
minimum = np.min(x, axis=1, keepdims=True)
maximum = np.max(x, axis=1, keepdims=True)
final = minimum/maximum
print(final)

[[0.6378259 ]
 [0.14067574]
 [0.11084006]
 [0.23470357]
 [0.44647271]]


In [ ]:
# 7) Normalize a 5x5 random 2D array along column:             2 point

In [394]:
x = np.random.rand(5,5)
mean = np.mean(x, axis=0)
numerator= x - mean
denominator= np.std(normalization, axis=0)
normalization = numerator / denominator
print(normalization)

[[ 0.19068601  1.01867216 -1.13369318 -0.45876672 -0.51445037]
 [-1.70243232 -0.03275065  0.56990117 -0.11293762  1.52862608]
 [ 1.08019285 -0.33797685  0.07367905  0.97746047  0.31628107]
 [-0.33418865 -1.02222158  0.92528573  0.74114356 -1.41071349]
 [ 0.76574211  0.37427691 -0.43517278 -1.1468997   0.08025671]]


In [155]:
# 8) Given a 1D random integer array within 100 with the size 20, get all items between 15 and 55, [15, 55].       4 points

In [392]:
x = np.random.randint(0, 100, 20)
result = x[(x >= 15) & (x <= 55)]
print(result)

[28 36 46 53 23 40 42 36 51]


In [ ]:
# 9) Use arange() to create a 1D array from 0 to 20, [0,20) and replace all odd numbers with -1:                2 points

In [163]:
x= np.arange(20)
x[x % 2 != 0] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [ ]:
# 10) Use random number generator to create a 4D array with shape(3,4,3,4) and values [0,10); then do the sum over the last two axes. 4 points

In [171]:
x = np.random.randint(0,10,size=(3,4,3,4)) #creating array
print(x)

[[[[6 3 9 7]
   [6 3 0 4]
   [1 6 3 1]]

  [[5 6 8 2]
   [6 4 0 6]
   [5 1 8 5]]

  [[4 3 2 8]
   [4 2 7 4]
   [0 6 5 9]]

  [[3 9 6 8]
   [4 1 5 6]
   [9 0 1 5]]]


 [[[3 3 9 5]
   [4 7 8 3]
   [3 3 9 4]]

  [[9 5 9 2]
   [8 4 3 8]
   [5 3 4 1]]

  [[5 7 1 7]
   [5 2 4 4]
   [0 2 8 5]]

  [[8 3 5 5]
   [9 1 6 1]
   [4 1 5 3]]]


 [[[6 9 1 6]
   [6 1 3 3]
   [5 7 7 3]]

  [[4 3 6 6]
   [3 8 9 2]
   [6 8 5 3]]

  [[8 9 8 4]
   [0 0 7 7]
   [7 3 2 5]]

  [[9 6 8 3]
   [6 3 3 1]
   [6 1 5 7]]]]


In [174]:
axes = x.sum(axis=(-2, -1)) #sum over last 2 axes
print(axes)

[[49 56 54 57]
 [61 61 50 51]
 [57 63 60 58]]


In [175]:
#PART-3

In [ ]:
# 1) Given a 1d array: [ 3, 6, 9, 25, 10, 8]                      4 points

In [ ]:
# (1) To get all elements except the first:

In [176]:
x= np.array([ 3, 6, 9, 25, 10, 8])
print(x[1:])

[ 6  9 25 10  8]


In [ ]:
# (2) To get all elements except the last:

In [177]:
x= np.array([ 3, 6, 9, 25, 10, 8])
print(x[:-1])

[ 3  6  9 25 10]


In [ ]:
# (3) To get every other element of the array (operation from the first element):

In [178]:
x= np.array([ 3, 6, 9, 25, 10, 8])
print(x[::2])

[ 3  9 10]


In [ ]:
# (4) To reverse the array:

In [179]:
x= np.array([ 3, 6, 9, 25, 10, 8])
print(x[::-1])

[ 8 10 25  9  6  3]


In [ ]:
# 2) Multidimensional Arrays:               4 points

In [ ]:
# (1) create a 2D array with shape(8,4) and values [0,32).

In [191]:
x = np.arange(0,32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [185]:
# (2) set the 3rd element in the 1st row to 0.

In [192]:
x[0,2] = 0
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
# (3) print out the second column

In [193]:
print(x[:, 1])

[ 1  5  9 13 17 21 25 29]


In [ ]:
# (4) Get the 3x3 region from the array:

In [195]:
print(x[2:5,1:])

[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [ ]:
#3) Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the NumPy "slicing" method to realize.                4 points

In [204]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1 #row (0,2) and column(1,3)
x[1::2, ::2] = 1 #row(1,3) and column(0,2)
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [ ]:
# 4) Given a 2D array with shape(6,4) and values [0,20), please use fancy indexing to exchange the first row and the last row:  3 points

In [390]:
x = np.random.randint(0, 20, size=(6, 4))
print('Original array:')
print(x)
index = [0, -1]
rfirst = x[index[0], :]
rlast = x[index[1], :]
x[index] = [rlast, rfirst]
print('Swapped array:')
print(x)

Original array:
[[ 5 16 13 19]
 [16  5  4 13]
 [15  1  6 10]
 [10  8 18  9]
 [ 9 19  3 16]
 [ 4  4 14 11]]
Swapped array:
[[ 4  4 14 11]
 [16  5  4 13]
 [15  1  6 10]
 [10  8 18  9]
 [ 9 19  3 16]
 [ 5 16 13 19]]


In [ ]:
#PART-4

In [ ]:
# by using numpy approach (3 points)

In [247]:
x = np.arange(1, 7)
result = x[:, np.newaxis] * x
print(result)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [ ]:
# by using Python nested for-loop (3 points)

In [252]:
x = [[0 for m in range(6)] for n in range(6)]
for n in range(6):   #nested for-loops
    for m in range(6):
        x[n][m] = (n + 1) * (m + 1)
result = np.array(x)
print(result)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [ ]:
#2). Given a 1D array from random number generator with values within 1000 and size 100, please use argsort() and argpartition() to respectively get the 5 largest values of this array X.             6 points

In [382]:

x = np.random.randint(1000, size=100)

#5 largest values of x using argsort()
Isorted = np.argsort(x)
largeargsort = Isorted[-5:]
largest5sort = x[largeargsort]
print(largest5sort)

#5 largest values of x using argpartition()
Ipartition = np.argpartition(x, -5)[-5:]
largest5part = x[Ipartition]
print(largest5part)


[967 968 970 977 990]
[967 968 970 977 990]


In [ ]:
#PART-5

In [321]:
import pandas as pd

rain = pd.read_csv('hw1_rain.csv')['PRCP'].values

rainin = rain / 254.0   # convert mm to inches


In [322]:
print(rainin)

[0.         0.16141732 0.05905512 0.         0.         0.01181102
 0.48031496 0.38188976 0.22834646 0.16929134 0.83858268 0.05905512
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.01968504 0.         0.
 0.         0.         0.         0.3503937  0.8503937  0.
 0.09055118 0.07874016 0.         0.         0.         0.
 0.         0.         0.2007874  0.01968504 0.72047244 0.66929134
 0.18110236 0.07086614 0.37007874 0.46062992 1.03937008 0.57086614
 0.5984252  0.03937008 0.11811024 0.11023622 0.0984252  0.24015748
 0.51181102 0.01181102 0.         0.         0.         0.01968504
 0.7519685  0.42125984 0.6496063  1.83858268 0.11811024 0.
 1.27165354 0.16929134 0.74015748 0.         0.         0.01968504
 0.27165354 0.31889764 1.09055118 0.01181102 0.         0.01968504
 0.         0.         0.         0.         0.         0.16141732
 0.14173228 0.01181102 0.87007874 0.5511811  0.         0.
 0.         0.         0.0984252  0.       

In [314]:
# Calculate the number of days without rain.     2 points

In [323]:
a = (rainin == 0).sum()
print("Number of days without rain:", a)

Number of days without rain: 215


In [ ]:
# Calculate the number of days with rain.        2 points

In [432]:
a = (rainin > 0).sum()
print("Number of days with rain:", a)

Number of days with rain: 150


In [ ]:
#Calculate the number of days more than 0.5 inches rainfall.   2 points

In [326]:
a = (rainin > 0.5).sum()
print("Number of days with more than 0.5 inches rainfall:", a)

Number of days with more than 0.5 inches rainfall: 37


In [291]:
#Calculate the number of days with rainfall between 0.5 and 1.0 inches   2 points

In [325]:
a = ((rainin >= 0.5) & (rainin <= 1.0)).sum()
print("Number of days with rainfall between 0.5 and 1.0 inches:", a)

Number of days with rainfall between 0.5 and 1.0 inches: 32


In [ ]:
#Construct a mask of all rainy days.  3 points

In [335]:
norain = 0
rainydays = rainin > norain
print(rainydays)

[False  True  True False False  True  True  True  True  True  True  True
 False False False False False False False False False  True False False
 False False False  True  True False  True  True False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False  True
  True  True  True  True  True False  True  True  True False False  True
  True  True  True  True False  True False False False False False  True
  True  True  True  True False False False False  True False  True False
 False  True False False False False False False  True  True  True False
  True False  True  True  True  True False  True  True False False False
 False False  True  True  True False False  True  True  True False False
 False False False False False False False False False False  True False
  True False False False False False False False False False False False
 False False False False False False  True  True Fa

In [ ]:
# Construct a mask of all summer days. All summer days can be counted from June 1st to August 31st. 3 points

In [336]:
wholeyear = np.arange(1, len(rainin) + 1)
summerdays = np.logical_and(wholeyear >= 152, wholeyear <= 243)
print(summerdays)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [ ]:
# Calculate median precip (precipitation) on rainy days in this year.   3 points

In [379]:
norain = 0
rainydays = rainin[rainin > norain]
median = np.median(rainydays)
print(median)

0.19488188976377951


In [ ]:
# Calculate median precip (precipitation) on summer days in this year.   3 points

In [366]:
summerdays = np.arange(152, 244)
summerprec = rainin[summerdays]
print(summerprec)

median = np.median(summerprec)
print(median)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.07086614 0.2519685
 0.         0.01968504 0.14173228 0.0511811  0.         0.03149606
 0.01181102 0.         0.         0.         0.         0.
 0.         0.07086614 0.09055118 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.01181102 0.75984252 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.01968504 0.         0.         0.         0.
 0.         0.         0.         0.         0.01968504 0.5
 0.8503937  0.         0.03937008 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.33070866
 0.0511811  0.        ]
0.0


In [367]:
print(median)

0.0


In [ ]:
# Calculate maximum precip on summer days in this year.  3 points

In [370]:
wholeyear = np.arange(1, len(rainin) + 1)
summerdays = np.logical_and(wholeyear >= 152, wholeyear <= 243)
summerprec = rainin[summerdays]
maxprec = np.max(summerprec)
print(maxprec)

0.8503937007874016


In [ ]:
# Calculate median precip on non-summer rainy days in this year.   3points

In [377]:
wholeyear = np.arange(1, len(rainin) + 1)  
summerdays = np.logical_and(wholeyear >= 152, wholeyear <= 243)
rainydays = rainin > 0
nonsummer_rainydays = np.logical_and(np.logical_not(summerdays), rainydays)
precipitation = rainin[nonsummer_rainydays]
median = np.median(precipitation)
print(median)

0.2047244094488189
